export const en = {
  language: "English",
  shopByCategory: {
    electronics: "Electronics",
    schoolSupplies: "School Supplies",
    toys: "Toys",
    communications: "Communications",
    seeMore: "See More",
  },
  home:{
    category:"All Categories ",
    hotSales:"Hot sales",
    hotSalesPragaph:"Shop the best prices and set your perfect outdoor vibe",
    popularItems:"Popular Items",
    dealsOfTheWeek:"Deals Of The Week",
    expires:"Expires in",
    bestPicks:"Best Picks",
    search:"search product",
    login:"Login",
    signup:"Sign up",
    shopByCategories:"Shop By Categories",
  },
  bestSeller:{
    bestSeller:"Best Seller",
    disc: "Shop the best prices and set your prefect outdoor vibe",
  },
  blog: {
    blog: "Our Blog",
    disc: "Shop the best prices and set your prefect outdoor vibe",
  },

  footer: {
    aboutOffer: "About Offer",
    aboutus: "About us",
    freeShippig: "REE SHIPPING WORLDWIDE",
    moneyBack: "MONEY BACK GUARANTEE",
    lowerPrice: "LOWEST PRICE GUARANTEE",
    support: "ONLINE SUPPORT 24/24",
    pragraph:"Rendered her for put improved concerns his. Ladies bed wisdom theirs mrs men months set. Everything so dispatched as it increasing pianoforte. Hearing now saw perhaps minutes herself his. Of instantly excellent therefore difficult he northward. Joy green but least",
    payment:"PAYMENT METHODS",
 customer:"CUSTOMER CARE ",
 contect:"Contact us",
 askSupport:"Ask Support",
 help:"Help",
 getInTouch:"Get In Touch",
terms:"Terms & conditions",
returns:"Returns",
privacy:"Privacy policy",
track:" Track Order",
blog:"Blog"
  },
  privacy:{
    titlePragraph:"Shop the best prices and set your perfect outdoor vibe",
    pragraph:"We thank you for visiting our site. We here at More Place do our best to win our customers over when they purchase our multiple products, and here we affirm our commitment that your privacy as our customer has no limits. Moreover, we are also committed to protecting and preserving consumer privacy on the Internet. We are pleased to provide information to all customers about the privacy policy on the Internet, and here we assure our customers of our efforts to protect the privacy of visitors to this site. ",
    typeTitle:"Types of information we collect and how we use it:",
 typePragraph:"Place Over collects personal information, such as: first and last (family) name, postal address, and e-mail (e-mail) addresses, and certainly this information is provided by the customer voluntarily and by your choice. For example: We collect personal information from you in order to obtain your feedback on our web sites and express your opinions on our products, or if you enter one of our contests or raffles. ",
sharing:"Sharing personal information:",
firstSharingPragraph:"Place Over may share your personal information only within the Place Over Group, which includes the Place Over Group family and its subsidiaries, and of course any use of this information by the Place Over Group will comply with this policy, sometimes and after obtaining your permission we will send you the information Marketing, such as discount coupons, information on new product offers....etc. If you are not selected to receive such information, More Place may assign some companies to perform a variety of functions such as: executing work orders, assisting in promotion work, providing technical services to websites...etc. These companies can access the customer's personal information if it is necessary to perform such tasks, and therefore such companies are bound by the privacy policy when using such personal information for the purpose of performing that job assigned to the company and therefore such personal information cannot be used for any other purpose.",
secondSharingPagraph:"Place Over is committed not to sell, transfer, or disclose customer personal information to any third parties outside the Place Over family family. However, with permission from the customer, we sometimes send marketing information on behalf of one of our business partners about products or services that we provide which may be of interest to the customer. Here, you may be asked if you wish to receive marketing materials from Partners of More Place Company or not. If you choose to receive such marketing materials, PlaceOver will not share your personal information with these partners, but will send such marketing materials by post or email on behalf of the Partners, PlaceOver reserves the right to use or disclose any information as needed To meet the requirements and instructions of any law, regulation or litigation, to protect the integrity of the Site, to fulfill your requests, to cooperate with the appropriate authorities in the investigation and enforcement of applicable laws or to investigate a matter of public safety. ",
},
terms:{
  welcomeTitle:"Welcome to a better place...",
  termsOfUs:"Terms of use",
  welcomeOne:"These terms and conditions define the rules and regulations for using a more over-the-top website.  ",
  weclomeTwo:"The site is operated by a more efficient place(referred to as  nh/us/or plural).",
  weclomeThree:"As a user of the website (referred to as you/you/customer) you must read and understand the following terms and conditions (list of  terms and conditions).",  
  welcomefour:"Once you use the website for purchase, you will be obliged to follow the terms and conditions. Please review the list of terms and conditions accurately before you start using electronic services.  In the event of disapproval (or  do not comply  with)any law or condition of the list, we advise you not to use the electronic services provided by a more efficient place.The office of the main place is located in:",
  welcomefive:" In Al-Mounsiya, Riyadh, Al-Tiser Street.",
  firsttermsPragraph:"The use of website services is only available to people who are able to legally represent themselves in accordance with the Saudi Arabian system.",
  secondTermsPragraph:"People who are unable to legally represent themselves under the local contract system cannot use the services of the website.",
 fourthTermsParagraph:"The user will be responsible for using the site's services from outside Saudi Arabia in full compliance with the local laws in that region.",
 fifthTermsPragraph:"These terms and conditions are valid and null and void for previous forms of commercial representation, oral agreements or other understandings unless additional conditions are allocated for a particular product orservice.",
 sixthTermsPragraph:"By using the website services you will be obliged to follow the terms andconditions.", 
 securityTitle:"Website security protection",
 communicationTitle:"electronic communication",
 firstcommunicationPragraph:"By agreeing to use the website and our electronic services, you agree to receive our emails in all its forms through email, newsletters, notices and alerts advertised on the website. Accordingly, you implicitly agree that all electronic transactions sent to you byus are legally binding and  treat  written transactions.",
 secondcommunicationPragraph:"We have the right to monitor, record and save any phone call, email or other form of electronic communication with you for training purposes in order to verify the advice and feedback addressed to us and to improve and develop the quality of service provided to our customers.",
supTitle:"You are never allowed to violate or attempt to violate the security protection of the website, which includes and is not limited to thefollowing:",
listOne:"	Access to information that is not intended for you or access to an internet server or account that you are not officially authorized touse.",
listtwo:"Try to explore, examine, test the ability of the system or network, or try to penetrate the security system or protection levels without being authorized to doso.",
listthree:"Attempting to interfere with the service provided to any other user, host, network or host that includes without limiting the deployment and transmission of viruses to the website,   overloading the site, sending serial messages, spam or any other means that may harm the integrity ofthenetwork.",
listfour:"Send spam, including trade offers and/or ads for products orservices",
listfive:"Simulation for the purpose of forgery curse the INTERNET protocol, email address or any part of the website address and use it in any email or mailing group.",
secondListFive:"You agree not to use system resources from devices, programs, any way to jam, overlap, or try to interfere with the workflow of the website or any activity or service provided by the site. The website will investigate activities that may involve such violations and will cooperate with the competent judicial authorities to prosecute and apply the necessary punishment to persons involved in suchviolations.",

},
conactus:{
  pragraph:"Shop the best prices and set your perfect outdoor vibe",
  submit:"Submit",
  ContactForm:"Contact Form",
  mesAlert:"* All fields marked with a asterisk are required",
  name:"Name *",
  email: "E-mail *",
  Message:"Message *",
  alert:"Please Fill all the filed",
  ContactInfo:"Contact Info",
  ContactInfoMsg:"Have a project or an idea you’d like to collaborate with Us? Let’s get in touch!",
  addresstitle:"Location:",
  callHelping:"Call Us:",
  mailInfotitle:"Email:",
},
aboutus:{
  pragraph:"Shop the best prices and set your perfect outdoor vibe",
  pragraphOne:"MakanOver and its website “offer site” launched a comprehensive station for electronics, home appliances and air conditioners, ………… which provides brands Global and local business with excellence and quality at reasonable prices....",
pragraphTwo:"A Saudi institution that has been at your service since 2000. A general trading institution specialized in providing everything that is new and of quality in various fields, which has now turned into a company in 2021.",
pragraphtThree:"We strive to always be the best, so our goal is to satisfy our customers with high quality products, provide the best level of service with the best prices, and facilitate purchase by various payment methods (electronic - and installments - and recently on credit)",
pragraphfour:"We provide shipping service all over the Kingdom.",
pragraphFive:"The idea behind the Over brand identity is inspired by offering promotions periodically.",
pragraphSix:"Our company is proud of its alliance with major companies such as: Lebara - Virgin - Saudi Telecom - Salam - Hikvision - Kenai - Ferrari - Dodo - Hilocity - Lulu Caty - Head - Zebra - Tzablo - Beck - Akaf - Aldafh - Drush - Pioneer - Bruges - Al Aseel .",
pragraphSeven:"The company has a strong presence in the field of marketing and distribution, as the distribution network covers sales channels for all markets and even individuals. The company is proud of having the trust and loyalty of the end consumer, and the company seeks to retain its customers for many years to come through the level of sales and after sales services.",
missionPragraph:"To be a leading global company that provides everything the consumer needs. Of high quality products at competitive prices that satisfy all customers, while providing all convenient ways to purchase that suit everyone.  ",
Whoweare:"Who we are ?",
aboutTitle:"After years of success in providing high quality products and services",
visionMission :"vision & mission ",
vissionTitle:"Our vision and mission ",
vissionPagraph:"To be a leading global company"
},
blogDetails:{
  Sharepost: "Share post",
  mostViewed:"Most Viewed",
  productName:"Add product name here in this space ",

},
productDetails:{
  relatedProducts:"Related products",
  Description:"Description",
  Reviews:"Reviews",
  descPragraph:"The Aspire 5 is a compact laptop in a thin case with a metal cover, a high-quality Full HD IPS display and a rich set of interfaces. Thanks to its powerful components, the laptop can handle resource-intensive tasks perfectly and is also suitable for most games.",
  KeyFeatures:"Key Features:  ",
  ShareProduct:"Share Product",
  Categories:"Categories :",
  productPragraph:"Place Over may share your personal information only within the Place Over Group, which includes the Place Over Group family and its subsidiaries, and of course any use of this information by the Place Over Group will comply with this policy, sometimes and after",
  addToCart:"Add to cart",
  saveToWishlist:"Save to wishlist",
  InStock:"In Stock",
}
};
